Plane-Shift Kaladesh: Servo Familiar
aurorabuilder/elements pull request #559
Opened 2020-07-31 14:42 UTC by JayPea00101010

I added it to the feat XML bc that's the only way to get a servo familiar.

Also sorry if it's not great code, never done a familiar, and made on Git, so I haven't tested it

2020-07-31 14:43 UTC, JayPea00101010 commented
Oh, I did bildgewater on my master branch, oops

2020-07-31 14:47 UTC, JayPea00101010 commented
deleted bildgewater stuff and changed update number

2020-08-01 12:46 UTC, swdriessen requested changes
Let me know when you've tested it. It saves me a lot of time to know that it at least works and that if something is incorrect it can always be fixed later instead of adding something that breaks  ;)

2020-08-01 12:46 UTC, swdriessen commented on unearthed-arcana/planeshift/kaladesh/feats-kaladesh.xml
> +		<update version="0.0.1">
lets go up instead of down ;)

2020-08-01 12:46 UTC, swdriessen commented on unearthed-arcana/planeshift/kaladesh/feats-kaladesh.xml
> +			<set name="actions">ID_GFP_COFSA_COMPANION_ACTION_ANIMATE_IMAGE_PAPERCUT,ID_WOTC_MM_COMPANION_ACTION_IMP_INVISIBILITY</set>
incorrect actions

2020-10-16 19:06 UTC, swdriessen commented
This content repository is being archived. I am closing any pending issues and pull requests.
I'll be sharing more information about concrete changes at a later date on the website.

2020-10-16 19:06 UTC, closed without merging